{% set version = "0.15.0" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.zip
  sha256: aae1d6085c32eedd91c668caea29dfd5b8f6a00758ac95c6a5c93560c410a11f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    - nose

test:
  imports:
    - cgsn_parsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
