{% set version = "0.5.0" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.tar.gz
  sha256: 7149df02d8a77981247feed1837b079ec390eb9046a0afe523fb03305270bade

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    # - nose

test:
  imports:
    - cgsn_parsers

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
