{% set version = "0.4.2" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.tar.gz
  sha256: 80175404cb62b9b1536890d4423fc89ed76bc7fd9424b32829263e6ff68fd71f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - munch >=2.1.0
    - pytz

test:
  imports:
    - cgsn_parsers

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: 'parsers for converting raw data from the OOI moorings'

extra:
  recipe-maintainers:
    - ocefpaf
