{% set version = "0.16.2" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.zip
  sha256: a8c137bf938620815fdcffd6b3750bd9a8044558ba6dc9bb05383dee0562a829

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    - nose

test:
  imports:
    - cgsn_parsers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
