{% set version = "0.16.5" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.zip
  sha256: aa99c6755493eb7599d8de13618904d23fee6980ce7a49d09c1ec01a40ec127f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    - nose

test:
  imports:
    - cgsn_parsers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
