{% set version = "0.7.0" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.tar.gz
  sha256: 8c4bd74b6f6fb778ec60c0ac8a490e8c19b2340465c357236752047bf6fbe472

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    - nose

test:
  imports:
    - cgsn_parsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
