{% set version = "0.16.3" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.zip
  sha256: 73ef7831dadb54ada9bd5b8e8a94927c7cd7d45c68277f98b6bbce121e477a38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    - nose

test:
  imports:
    - cgsn_parsers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: parsers for converting raw data from the OOI moorings

extra:
  recipe-maintainers:
    - ocefpaf
