{% set version = "0.4.8" %}

package:
  name: cgsn_parsers
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-parsers/get/{{ version }}.tar.gz
  sha256: 3cda63267a99be0b04bfeb9cc4b5f425f8f878121b252ddac7376e8c192060aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - munch >=2.1.0
    - pytz
    - pandas
    # - nose

test:
  imports:
    - cgsn_parsers

about:
  home: https://bitbucket.org/ooicgsn/cgsn-parsers
  license: MIT
  license_file: LICENSE.txt
  summary: 'parsers for converting raw data from the OOI moorings'

extra:
  recipe-maintainers:
    - ocefpaf
