travis:
  secure:
    BINSTAR_TOKEN: Pv36VwRuE63z1nSbWlbJ7G+ZM//PKpj4oHdZhjZZ339QfyiE+H8kcYYcrKpkgy5imXfmoQF97m7U975wK+ArT4qQXUiS3fLV6rcr/suD9RQ/cHPzLzGRHmIRgi3PMZ3ZxRRTiUmudzAagpxNv46QSbreg78Balqn1FgRygPrvvnE/FRW6UCqSYMD9JD+JeVV/85rT+ewv9N+gtjS9JHXfxlBLxoM6fHodsSQ43tx72glCBiHdfk+3p5FxaKqk7H9sb4acDHWJGtuWQNV8rNiy0raTCsvvwVl4qThvwgBAUBL6LfG5BVF8lTJBCafFobbi0wW5uyt82JSDQbXaBwsWh3bbO0saFJV6H4///CbCVKxitruJF7kB8Ow96O3buStZjpLJoXgzuQ3zEFRar13IWNmGwoi38LksGFz/Cyb7bVUz0367Htj8UEshro+NzZgTdvzlJVdXWITdKDLcHDy5oD2WIhhOtSNR1gx8g5hya/Kb2N854Eyx0tTjjuf2tI6pTRFCNqK0xgsZHTnfrI4ZYjNYeEVLym1RpJP5l3ElizTXNQiwnoTMHOPfTiSvhkHlLD9RVaYTyfcioY/TnLekeW7syh90lPiB7mzZVUsW7BUmNEqd58YxymjztNEChVB2CM3XBwEhQJHQnJIuSUvTmo/Bkjgif4wTY6yYVyh6J4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
