travis:
  secure:
    BINSTAR_TOKEN: pFvBKE4wer8gb63G7nxR7Qvp6mu3bzC6SINYgc3HlixoXBsnGtU3TUD1IW1YRznwyDhyx8Z1eQ8CahNabyFb3/EC9J7a3Adzq74qfFZQDkG8HIWLMjM1IEid1wM0rcq6vApbBkOcvkNPiuFzp+gbuwAhTN/W6MkMJsYPhKunqih12Fc1lTpUT/M9fyZ+hoUmCU9Xo1IVBINoTBX9AEKSaZpjAMuPTZX8vE5ADv2dwBV4nXr66Rh7thyzxWYGyrNwxJK9PD9WaCcYEVVt0N7jD97pf8I3NbYk8NC7NP+Sqn+fwomrzmTqv0ob8b9x3/0yHjxgHAQxmQRuyPdcplzluKi0AyBSnpP9yPTPDqAsPf38RJK3k7l01U9nL1p/TSNh/znpfAwI47olijTJ2yjDaqBpQ2NcNu8qmM6Y60E4uovlEch6OPiq4L179/UPD6j7cQao5GrIbta28cNKeRxwQVEzJ8/omPjLCy30zcVljFM9iGxn7/+gntWNUmhpi3AYiUWPO0ZHxbctCX0IQ+rRCq+yIw37nv/Dr8yVg9Obo2vL8QXCPYmEzVu+67f7y1vEM6SOsiQrvUiCkBZIKKJZii6lI6ysxeDxuFDyIRI9ffr+RR1yNxb4jx3Z4eaKL2FXzrrH4z9aQSsTAfu2sv8bza2LSpyBsAxNjVMoFOaO0IM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
